apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  namespace: deployments
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      nodeSelector:
        workload: monitoring
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80