apiVersion: v1
kind: Namespace
metadata:
  name: deployments

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: deployments
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.22.0
          ports:
            - containerPort: 80