apiVersion: v1
kind: Namespace
metadata:
  name: storage-lab

---
apiVersion: v1
kind: Pod
metadata:
  name: shared-storage-pod
  namespace: storage-lab
spec:
  containers:
    - name: writer
      image: busybox:1.36
      command:
        - sh
        - -c
        - while true; do date > /shared/time.txt; sleep 5; done
      volumeMounts:
        - name: shared-data
          mountPath: /shared

    - name: reader
      image: busybox:1.36
      command:
        - sh
        - -c
        - while true; do cat /shared/time.txt 2>/dev/null || true; sleep 5; done
      volumeMounts:
        - name: shared-data
          mountPath: /shared

  volumes:
    - name: shared-data
      emptyDir: {}