apiVersion: v1
kind: Pod
metadata:
  name: shared-pod
  labels:
    app: shared-demo
spec:
  containers:
    - name: web-server
      image: nginx:1.27
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

    - name: content-writer
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date > /html/index.html; sleep 5; done
      volumeMounts:
        - name: shared-data
          mountPath: /html

  volumes:
    - name: shared-data
      emptyDir: {}